# Generated by Django 2.2.5 on 2020-02-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200217_0517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
