# Generated by Django 2.2.5 on 2020-02-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200217_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='primaryCategory',
        ),
    ]
