# Generated by Django 2.2.5 on 2020-02-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_category_primarycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='ABC', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(default='ABCE', on_delete=django.db.models.deletion.CASCADE, to='task.Location'),
            preserve_default=False,
        ),
    ]
