# Generated by Django 2.2.5 on 2020-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200217_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
