# Generated by Django 2.2.5 on 2020-02-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200217_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
