# Generated by Django 2.2.5 on 2020-02-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
